services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./config/env/.env
    depends_on:
      - db
  db:
    image: postgres:15.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/env/db.env
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
  celery:
    build:
      context: .
      dockerfile: ./config/celery/Dockerfile
    command: celery -A base worker -l INFO
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./config/env/.env
    depends_on:
      - redis
volumes:
  postgres_data:
