# Generated by Django 4.1.7 on 2023-03-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0002_alter_datatype_extra_args'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatype',
            name='extra_args',
        ),
        migrations.AddField(
            model_name='datatype',
            name='extra_args',
            field=models.ManyToManyField(to='data_schemas.arguments'),
        ),
    ]
