# Generated by Django 4.1.7 on 2023-03-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0003_remove_datatype_extra_args_datatype_extra_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='extra_args',
            field=models.ManyToManyField(blank=True, to='data_schemas.arguments'),
        ),
    ]
