# Generated by Django 4.1.7 on 2023-03-05 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_schemas', '0004_alter_datatype_extra_args'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataschema',
            name='columns',
        ),
        migrations.AddField(
            model_name='column',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_schemas.dataschema'),
            preserve_default=False,
        ),
    ]
