# Generated by Django 4.1.7 on 2023-03-05 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_schemas', '0006_alter_column_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sets', to='data_schemas.dataschema')),
            ],
        ),
    ]
